const weatherData = [
    {
        id: 1,
        date: '2021/03/01',
        minTemp: 9,
        maxTemp: 13,
        pressure: 756,
        humidity: 82,
        windSpeed: 3.0,
        windDirection: 'N',
        generalDescription: 'Mostly Sunny',
    },
    {
        id: 2,
        date: '2021/03/02',
        minTemp: 10,
        maxTemp: 14,
        pressure: 740,
        humidity: 75,
        windSpeed: 1.5,
        windDirection: 'NE',
        generalDescription: 'Sunny',
    },
    {
        id: 3,
        date: '2021/03/03',
        minTemp: 5,
        maxTemp: 10,
        pressure: 780,
        humidity: 90,
        windSpeed: 5.0,
        windDirection: 'E',
        generalDescription: 'Rain',
    },
    {
        id: 4,
        date: '2021/03/04',
        minTemp: 1,
        maxTemp: 5,
        pressure: 782,
        humidity: 92,
        windSpeed: 2.0,
        windDirection: 'SW',
        generalDescription: 'Rain/Snow',
    },
    {
        id: 5,
        date: '2021/03/05',
        minTemp: -1,
        maxTemp: 3,
        pressure: 781,
        humidity: 80,
        windSpeed: 4.0,
        windDirection: 'S',
        generalDescription: 'Snow',
    },
    {
        id: 6,
        date: '2021/03/06',
        minTemp: 2,
        maxTemp: 5,
        pressure: 790,
        humidity: 75,
        windSpeed: 2.0,
        windDirection: 'SW',
        generalDescription: 'Mostly Cloudy',
    },
    {
        id: 7,
        date: '2021/03/07',
        minTemp: 5,
        maxTemp: 10,
        pressure: 740,
        humidity: 70,
        windSpeed: 1.0,
        windDirection: 'NW',
        generalDescription: 'Cloudy',
    },
];

export default weatherData;
